// This block controls Isaac's timer. 
IF
InParty(Myself)
RealGlobalTimerExpired("X3IsaacTimer","GLOBAL")
See(Player1)
!StateCheck(Player1,CD_STATE_NOTVALID)    
!StateCheck(Myself,CD_STATE_NOTVALID)
CombatCounter(0)                          
!See([ENEMY])
!AreaType(DUNGEON)			  
Global("X3IsaacTalk","GLOBAL",15)
THEN
RESPONSE #100
IncrementGlobal("X3IsaacTalk","GLOBAL",1)
StartDialogueNoSet(Player1)
END