// ITEMS

LOAD_TRA ~Emily/tra/English/Emil_bg1.tra~

COPY_EXISTING ~Emily/Item/X3EQRL.itm~ ~override/X3EQRL.itm~
SAY NAME1 @50
SAY NAME2 @50
SAY DESC @51 
  LPF ALTER_EFFECT
      INT_VAR
      match_opcode = 15
      parameter1 = 1
    END

COPY_EXISTING ~Emily/Item/X3EQRX.itm~ ~override/X3EQRX.itm~
SAY NAME1 @52
SAY NAME2 @52
SAY DESC  @53
  LPF ALTER_EFFECT
      INT_VAR
      match_opcode = 15
      parameter1 = 1
    END
	
COPY_EXISTING ~Emily/Item/X3EQRLS.itm~ ~override/X3EQRLS.itm~
SAY NAME1 @59
SAY NAME2 @59
SAY DESC @60
  LPF ALTER_EFFECT
      INT_VAR
      match_opcode = 15
      parameter1 = 1
    END

COPY_EXISTING ~Emily/Item/X3EQRXL.itm~ ~override/X3EQRXL.itm~
SAY NAME1 @58
SAY NAME2 @58
SAY DESC  @59
  LPF ALTER_EFFECT
      INT_VAR
      match_opcode = 15
      parameter1 = 1
    END

COPY_EXISTING ~Emily/Item/X3EGem.itm~ ~override/X3EGem.itm~
SAY NAME1 @61
SAY NAME2 @61
SAY DESC  @62

COPY_EXISTING ~Emily/Item/X3EJorn.itm~ ~override/X3EJorn.itm~
SAY NAME1 @63
SAY NAME2 @63
SAY DESC  @64	

COPY_EXISTING ~Emily/Item/X3EBLOOD.itm~ ~override/X3EBLOOD.itm~
SAY NAME1 @65
SAY NAME2 @65 
SAY DESC @66 

  // Items 
  
 COPY ~%MOD_FOLDER%/eff/X3ECELT.eff~ ~override~ 
 COPY ~%MOD_FOLDER%/eff/X3EDEMT.eff~ ~override~
 COPY ~%MOD_FOLDER%/eff/X3ETIEFT.eff~ ~override~  
 COPY ~%MOD_FOLDER%/eff/X3ERACD.eff~ ~override~ 
 COPY_EXISTING ~%MOD_FOLDER%/Item/X3ESWRD.itm~ ~override~
 SAY NAME1 @67
 SAY NAME2 @67 
 SAY DESC @68
 
 COPY_EXISTING ~Emily/Item/X3ESB1.itm~ ~override/X3ESB1.itm~
SAY NAME1 @69
SAY NAME2 @69 
SAY DESC @70 


   COPY_EXISTING ~%MOD_FOLDER%/Item/x3EArrow.bam~ ~override/x3EArrow.bam~
    COPY_EXISTING ~%MOD_FOLDER%/Item/x3EBolt.bam~ ~override/x3EBolt.bam~
 COPY_EXISTING ~%MOD_FOLDER%/Item/x3EArro1.itm~ ~override/x3EArro1.itm~
SAY NAME1 @72
SAY NAME2 @72
SAY DESC @82
    LPF ADD_ITEM_EQEFFECT
    INT_VAR
      opcode = 319
	  target = 1
	  timing = 2
	  parameter2 = 11
	  power = 1
	  special = RESOLVE_STR_REF (@1)
	STR_VAR
	  resource = X3mily
END

 COPY_EXISTING ~%MOD_FOLDER%/Item/x3EArro2.itm~ ~override/x3EArro2.itm~
SAY NAME1 @73
SAY NAME2 @73
SAY DESC @83
    LPF ADD_ITEM_EQEFFECT
    INT_VAR
      opcode = 319
	  target = 1
	  timing = 2
	  parameter2 = 11
	  power = 1
	  special = RESOLVE_STR_REF (@1)
	STR_VAR
	  resource = X3mily
END

 COPY_EXISTING ~%MOD_FOLDER%/Item/x3EArro3.itm~ ~override/x3EArro3.itm~
SAY NAME1 @74
SAY NAME2 @74
SAY DESC @84
    LPF ADD_ITEM_EQEFFECT
    INT_VAR
      opcode = 319
	  target = 1
	  timing = 2
	  parameter2 = 11
	  power = 1
	  special = RESOLVE_STR_REF (@1)
	STR_VAR
	  resource = X3mily
END

 COPY_EXISTING ~%MOD_FOLDER%/Item/x3EArro4.itm~ ~override/x3EArro4.itm~
SAY NAME1 @75
SAY NAME2 @75
SAY DESC @85

COPY_EXISTING ~%MOD_FOLDER%/Item/x3EBolt1.itm~ ~override/x3EBolt1.itm~
SAY NAME1 @76
SAY NAME2 @76
SAY DESC @86
    LPF ADD_ITEM_EQEFFECT
    INT_VAR
      opcode = 319
	  target = 1
	  timing = 2
	  parameter2 = 11
	  power = 1
	  special = RESOLVE_STR_REF (@1)
	STR_VAR
	  resource = X3mily
END

 COPY_EXISTING ~%MOD_FOLDER%/Item/x3EBolt2.itm~ ~override/x3EBolt2.itm~
SAY NAME1 @77
SAY NAME2 @77
SAY DESC @87
    LPF ADD_ITEM_EQEFFECT
    INT_VAR
      opcode = 319
	  target = 1
	  timing = 2
	  parameter2 = 11
	  power = 1
	  special = RESOLVE_STR_REF (@1)
	STR_VAR
	  resource = X3mily
END

 COPY_EXISTING ~%MOD_FOLDER%/Item/x3EBolt3.itm~ ~override/x3EBolt3.itm~
SAY NAME1 @78
SAY NAME2 @78
SAY DESC @88
    LPF ADD_ITEM_EQEFFECT
    INT_VAR
      opcode = 319
	  target = 1
	  timing = 2
	  parameter2 = 11
	  power = 1
	  special = RESOLVE_STR_REF (@1)
	STR_VAR
	  resource = X3mily
END

 COPY_EXISTING ~%MOD_FOLDER%/Item/x3EBolt4.itm~ ~override/x3EBolt4.itm~
SAY NAME1 @79
SAY NAME2 @79
SAY DESC @89 


//Spell
COPY	"%MOD_FOLDER%/Item/X3EFA.spl" override
	SAY NAME1 @80
	SAY NAME2 @80
	SAY 0x50 @90
	//Spell
COPY	"%MOD_FOLDER%/Item/X3EFB.spl" override
	SAY NAME1 @81
	SAY NAME2 @81
	SAY 0x50 @91