/*bdcut61.baf */
IF
	InParty("X3mily")  
THEN
	RESPONSE #100
		CutSceneId(Player1)
		ActionOverride("X3mily",LeaveParty())
		SetGlobal("X3mily_SoDparty_epilogue","GLOBAL",1) 
		SetGlobal("X3milyKickedOut","GLOBAL",1) //this is for inner mod detection, for example if the game's a continuous EET game. Put here whatever you need for your own mod.
		ActionOverride("X3mily",DestroyAllFragileEquipment(ADAMANTINE)) //this destroys all drow equipment, just in case the NPC had any.
END

